### ISSUE TITLE
Automated testing and coverage report

### ISSUE THREAD

**Issue by paazmaya** [paazmaya/tawata#3]
- [ ] Travis CI
- [ ] codecov.io
- [ ] AppVeyor

**Comment by gargi** [comment]
@paazmaya Can I work on this?

**Comment by paazmaya** [comment]
@gsrajadh Sure!

**Comment by gargi** [comment]
@paazmaya Thanks! I will work on this over the weekend

**Comment by gargi** [comment]
@paazmaya are there any tests for this? which I could automate. what exactly do I have to do?

**Comment by paazmaya** [comment]
There is #1 for unit tests and #2 for code coverage.

Once example of how they could be done: https://github.com/paazmaya/shuji
